# Generated by Django 4.0.5 on 2022-06-18 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_usertype_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="type", new_name="user_type",
        ),
        migrations.RenameField(
            model_name="usertype", old_name="type", new_name="user_type",
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_login_date", models.DateField(verbose_name="마지막 로그인 날짜")),
                ("last_job_apply_date", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
